name: ajLeaderboards
version: "@VERSION@"
main: us.ajg0702.leaderboards.LeaderboardPlugin
author: ajgeiss0702
depend: [PlaceholderAPI]
softdepend: [Vault, SkinsRestorer]
description: Leaderboards for your server
api-version: 1.13
folia-support: true
commands:
   ajleaderboards:
      aliases: [ajlb, ajl, alb]
      description: Commands for ajLeaderboards
      permission: ajleaderboards.use
permissions:
   ajleaderboards.use:
      description: Allows you to set up the plugin
      default: op
